# configs/kdcdm.yaml
model:
  name: KDCDDM
  teacher_model: CDLDM
  generator_channels: 128
  discriminator_channels: 128
train:
  lr_g: 0.0001
  lr_d: 0.0001
  batch_size: 16
  epochs: 100
  lambda_l1: 10.0
  ema_decay: 0.999
